added support for newer versions of papi
PlaceholderAPI/RedisBungee-Expansion pull request #2
Opened 2021-05-20 23:32 UTC by ham1255

2021-06-09 14:16 UTC, ham1255 commented
Is this pr is being ignored?

2021-06-29 11:55 UTC, ham1255 commented
Bumping this again.....

2021-06-29 12:14 UTC, ArjanSchoorl commented
This is very nice to include!

2021-06-30 13:53 UTC, darbyjack requested changes

2021-06-30 13:53 UTC, darbyjack commented on pom.xml
> +            <version>2.10.1</version>
Latest is 2.10.9, might want to compile against that just to be sure everything still works.

2021-06-30 13:53 UTC, darbyjack commented on src/main/java/com/helpchat/redisbungeeexpansion/RedisBungeeExpansion.java
> +            //for older version of papi support.
I'd honestly say drop support for older versions of PAPI. They don't receive support from us anymore. Compile against latest, ensure it works on latest, don't worry about doing hacks to make it work on previous versions.

2021-06-30 14:06 UTC, ham1255 commented
alright all requested changes will be pushed now.

2021-06-30 14:28 UTC, darbyjack commented
LGTM. Do you have any screenshots showing it's working? I don't have a RedisBungee environment setup.

2021-06-30 14:30 UTC, ham1255 commented
![image](https://user-images.githubusercontent.com/34905970/123978839-3ecdd080-d9d1-11eb-83cf-3d6526e125e0.png)
![image](https://user-images.githubusercontent.com/34905970/123978914-4ee5b000-d9d1-11eb-823e-48e9e00dcf06.png)

2021-06-30 14:33 UTC, darbyjack approved these changes

2021-06-30 14:33 UTC, merged